workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      sdk: "android-34"
    scripts:
      - name: Fix gradlew permissions
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your@email.com
