workflows:
  android-build:
    name: Android build without wrapper
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Build Debug APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
