workflows:
  android-build:
    name: Android build without wrapper
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Install Gradle
        script: |
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle -v
      - name: Build Debug APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
