workflows:
  android-build:
    name: Android Debug Build
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Fix gradlew permissions
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
