workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    scripts:
      - name: Fix gradlew permissions
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
