workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 20
    instance_type: mac_mini_m1

    environment:
      java: 17
      vars:
        PACKAGE_NAME: "com.suvenirafk.wordcounter"

    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
