name: Android CI (APK)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # leis paleisti ranka mygtuku "Run workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        gradle-version: 8.7
arguments: assembleRelease



- name: Build with Gradle
  uses: gradle/gradle-build-action@v2
  with:
    gradle-version: 8.7
    arguments: assembleRelease

- name: Upload APK
  uses: actions/upload-artifact@v4
  with:
    name: WordCounterApp-APK
    path: app/build/outputs/apk/release/*.apk
