name: Build Android APK

on:
  workflow_dispatch: # kad galėtum paleisti pats

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 1. Sugeneruojam wrapper
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.0

      # 2. Leidžiam teisę vykdyti
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 3. Build apk
      - name: Build with Gradle
        run: ./gradlew assembleRelease

      # 4. Įkeliam rezultatą
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: app/build/outputs/apk/release/*.apk
